### PR TITLE
fixed sending array in AJAX request

### LINKED ISSUE #202: Nette does not receive array
Naja version: 2.1.2

JS:

```
            year = '2020';
            paymentTags = {1,2};

            data = { year, paymentTags };

            naja.makeRequest('GET', "/?do=paymentsJS-changeYear", data)
```
obrazek

Nette receives

obrazek

### PR DESCRIPTION
**Pull request by petrparolek**
closes #202

### CODE REVIEW

**Comment by petrparolek** [comment]
thanks @DzeryCZ very much for providing a lot of helps with fixing.

**Comment by jiripudil** [comment]
Hello, first of all, thanks for the contribution, every helping hand counts!

This definitely goes in the right direction, but since this issue is already on the table, I'd like to have it fixed properly, i.e.

- Naja should transform everything that PHP and/or Nette can correctly parse, including arrays (`key[]=value`), objects (`key[subkey]=value`), and any arbitrarily nested structures (`key[subkey][0][subkey]=value`).
- In addition to GET and HEAD requests where data need to be serialized into the query string, the same transformation also needs to be done to `application/x-www-form-urlencoded` request body – currently it suffers from pretty much the same bug [on this line](https://github.com/jiripudil/Naja/blob/master/src/Naja.ts#L116).
- Needless to say, this kind of change needs a decent test coverage.

Let me know if you're willing to put more effort into this, I might have some thoughts on how this could be implemented. Otherwise I might be able to find some time to fix this during this or the following week. I believe this is not a blocker, as you can always build the URL in your code until this is fixed.

**Comment by petrparolek** [comment]
I am not good at Javascript. It's up to you. Could you fix it in your way?

**Comment by jiripudil** [comment]
> I am not good at Javascript. It's up to you. Could you fix it in your way?

Sure, no worries :) by the way your code is really not bad, it's just that the scope of the problem is larger than you expected.

**Comment by petrparolek** [comment]
code is from my friend @DzeryCZ .

**Comment by jiripudil** [comment]
Well then, thanks to both of you for putting your time and effort into this!

**Pull request closed without merging**
